export const CHORD_SECTION_PROVIDER = Symbol('CHORD_SECTION_PROVIDER');
export const LYRICS_SEARCH_PROVIDER = Symbol('LYRICS_SEARCH_PROVIDER');
export const AUDIOSHAKE_TRANSCRIPTION_PROVIDER = Symbol(
  'AUDIOSHAKE_TRANSCRIPTION_PROVIDER',
);
